language: R
cache:
  packages: true
  directories:
  - $HOME/.npm
  
pandoc_version: 2.3.1

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  
before_install:
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${TRAVIS_COMMIT_MESSAGE:0:70}"

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- nvm install stable
- npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
  skip_cleanup: true