language: R
cache:
  packages: true
  directories:
  - $HOME/.npm
  - _book
  
pandoc_version: 2.3.1

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true