# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm
pandoc_version: 2.3.1

before_install:
  - nvm install stable
  - npm install netlify-cli -g

env:
  - NETLIFY_SITE_ID=2a74e69e-e02c-4051-87ad-c3ac1ecedfd6
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod
    skip_cleanup: true
    on:
      branch: master