--- 
title: "Data Wrangling with R"
author: "Bradley Boehmke"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: references.bib
biblio-style: apalike
link-citations: yes
github-repo: bradleyboehmke/dw-r
twitter-handle: bradleyboehmke
description: "Master the art of data wrangling with the R programming language."
---

`r if (knitr::is_latex_output()) '<!--'` 

# Preface {-}

```{block, type = "note"}
This is the online version of the work-in-progress 2nd edition of ["_Data Wrangling with R_"](https://www.springer.com/us/book/9783319455983)
```

Welcome to the second edition of _Data Wrangling with R_! In this book, I will help you learn the essentials of preprocessing data leveraging the R programming language to easily and quickly turn noisy data into usable pieces of information. Data wrangling, which is also commonly referred to as data munging, transformation, manipulation, janitor work, etc. can be a painstakingly laborious process. In fact, it has been stated that up to 80% of data analysis is spent on the process of cleaning and preparing data [@tidy-data; @dasu2003exploratory]. However, being a prerequisite to the rest of the data analysis workflow (visualization, modeling, reporting), it's essential that you become fluent *and* efficient in data wrangling techniques.

This book will guide you through the data wrangling process along with give you a solid foundation of the basics of working with data in R. My goal is to teach you how to easily wrangle your data, so you can spend more time focused on understanding the content of your data via visualization, modeling, and reporting your results. By the time you finish reading this book, you will have learned how to work with the different data types and structures, acquire and parse data from locations you may not have been able to access before, manage control structures, implement efficient workflows, reshape and transform your data, and even perform tasks beyond the borders of your laptop.  In essence, you will have the data wrangling toolbox required for modern day data analysis.


## Who should read this {-}

This book is meant to establish the baseline R vocabulary and knowledge for the primary data wrangling processes.  This captures a wide range of programming activities which covers the full spectrum from understanding basic data objects in R to writing your own functions, applying loops, and webscraping.  As a result, this book can be beneficial to all levels of R programmers.  Beginner R programmers will gain a basic understanding of the functionality of R along with learning how to work with data using R.  Intermediate and/or advanced R programmers will likely find the early chapters reiterating established knowledge; however, these programmers will benefit from the mid and later chapters by learning newer and/or more efficient data wrangling techniques.  


## What You Need For this Book {-}

Obviously to gain and retain knowledge from this book it is highly recommended that you follow along and practice the code examples yourself.  Furthermore, this book assumes that you will actually be performing data wrangling in R; therefore, it is assumed that you have or plan to have R installed on your computer. You will find the latest version of R for Linux, Mac OS, and Windows at [cran.r-project.org/](https://cran.r-project.org/).  It is also recommended that you use an integrated development environment (IDE) as it will simplify and organize your coding environment greatly.  There are several to choose from; however, I highly recommend [RStudio](https://www.rstudio.com/).

## Conventions used in this book {-}

The following typographical conventions are used in this book:

* ___strong italic___: indicates new terms,
* __bold__: indicates package & file names,
* `inline code`: monospaced highlighted text indicates functions or other commands that could be typed literally by the user,
* code chunk: indicates commands or other text that could be typed literally by the user

```{r, first-code-chunk, collapse=TRUE}
1 + 2
```

In addition to the general text used throughout, you will notice the following code chunks with images:

```{block, type = "tip"}
Signifies a tip or suggestion
```

```{block, type = "note"}
Signifies a general note
```

```{block, type = "warning"}
Signifies a warning or caution
```

## Feedback {-}

Reader comments are greatly appreciated. To report errors or bugs please post an issue at https://github.com/bradleyboehmke/dw-r/issues.

## Acknowledgments {-} 

I'd like to thank everyone who contributed feedback, typo corrections, and discussions while the book was being written. TBD.

## Software information {-} 

This book was built with the following packages and R version.  All code was executed on 2017 MacBook Pro with a 2.9 GHz Intel Core i7 processor, 16 GB of memory, 2133 MHz speed, and double data rate synchronous dynamic random access memory (DDR3). 

```{r, collapse=TRUE, comment = "#>"}
# packages used
pkgs <- c(
  "completejourney",
  "tidyverse"
)

# package & session info
sessioninfo::session_info(pkgs)
```


`r if (knitr::is_latex_output()) '-->'`
