---
title: "Introduction to R"
author: NULL
date: NULL
output:
  html_document:
    keep_md: true
---


A language for data analysis and graphics. This definition of R was used by Ross Ihaka and Robert Gentleman in the title of their 1996 paper[^RR_paper] outlining their experience of designing and implementating the R software. Its safe to say this remains the essence of what R is; however, its tough to encapsulate such a diverse programming language into a single phrase.

During the last decade, the R programming language has become one of the most widely used tools for statistics and data science. Its application runs the gamut from data preprocessing, cleaning, web scraping and visualization to a wide range of analytic tasks such as computational statistics, econometrics, optimization, and natural language processing.  In 2012 R had over [2 million users](http://www.oracle.com/us/corporate/press/1515738) and continues to grow by double digit percentage points every year. R has become an essential analytic software throughout industry; being used by organizations such as Google, Facebook, New York Times, Twitter, Etsy, Department of Defense, and even in presidential political campaigns.

So what makes R such a popular tool? 

## History
R is an *open source* software created over 20 years ago by Ross Ihaka and Robert Gentleman at the University of Auckland, New Zealand. However, its history is even longer as its lineage goes back to the S programming language created by John Chambers out of Bell Labs back in the 1970s.[^naming] R is actually a combination of S with lexical scoping semantics inspired by Scheme.[^morandat] Whereas the resulting language is very similar in appearance to S, the underlying implementation and semantics are derived from Scheme. Unbeknownst to many the S language has been a popular vehicle for research in statistical methodology, and R provides an *open source* route to participate in that activity.

Although the history of S and R is interesting[^peng], the principal artifact to observe is that R is an *open source* software. Although some contest that open-source software is merely a "craze" [^ORMS], most evidence suggests that open-source is here to stay and represents a *new*[^newness] norm for programming languages. This invariably leads to new expectations for data analysts; this is evidenced by a recent O'Reilly survey revealing that data analysts focusing on open source technologies make more money than those still dealing in proprietary technologies. 

## Environment


## Community






[^RR_paper]: Ihaka, R., & Gentleman, R. (1996). R: a language for data analysis and graphics. *Journal of computational and graphical statistics*, 5(3), 299-314.
[^naming]: Consequently, R is named partly after its authors (Ross and Robert) and partly as a play on the name of S.
[^morandat]: Morandat, Frances; Hill, Brandon (2012). Evaluating the design of the R language: objects and functions for data analysis. *ECOOP'12 Proceedings of the 26th European conference on Object-Oriented Programming.*
[^peng]: See Roger Peng's [R programming for Data Science](https://leanpub.com/rprogramming) for further, yet concise, details on S and R's history.
[^ORMS]: Insert ORMS article by PKB
[^newness]: Open-source is far from new as its been around for decades (i.e. A-2 in the 1950s, IBM's ACP in the '60s, Tiny BASIC in the '70s) but has gained prominence since the late 1990s.